apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-deployment
  labels:
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: simple-api
          image: lfscovelo/simple-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: postgres-cluster-ip-service
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: postgres
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: postgres
            - name: REDIS_HOST
              value: redis-cluster-ip-service
