name: Deploy Simple API
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t lfscovelo/simple-api:latest -f Dockerfile .
      - run: docker tag lfscovelo/simple-api:latest
      - run: docker push lfscovelo/simple-api:latest
